module.exports = {
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,

  AWS_S3_IMAGES_BUCKET_REGION: process.env.AWS_S3_IMAGES_BUCKET_REGION,
  AWS_S3_IMAGES_BUCKET_NAME: process.env.AWS_S3_IMAGES_BUCKET_NAME,
}